name: W3C-DID CI
on: push
jobs:
  test-units:
    runs-on: ubuntu-latest
    name: 🧪 test-units
    steps:
      - uses: actions/checkout@v3
      - name: install Zenroom
        run: |
          sudo apt install wget 
          wget  https://sdk.dyne.org/view/zenroom/job/zenroom-static-amd64/lastSuccessfulBuild/artifact/src/zenroom -O zenroom
          chmod +x zenroom
          sudo cp zenroom /bin/
      - name: tests
        run: |
          make test-units

  restroom_job:
    runs-on: ubuntu-latest
    name: Start restroom and request a simple contract
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start restroom
        uses: dyne/restroom-github-action@v1
        with:
          restroom-contracts: "${{ github.workspace }}/contracts"
      - name: Install curl
        run: sudo apt install curl
      - name: Run tests
        run: ./test/run.sh
